name: Perform Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Test-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pogfi/pnpm-install-cache@v0.0.2
        name: Install pnpm

      - name: Build Package
        run: pnpm run -r build

      - name: Clean cache
        run: pnpm store prune
